spring:
  datasource:
    url: ${DB_URL_CM}
    username: ${DB_USER_CM}
    password: ${DB_PASS_CM}
    driver-class-name: ${DB_DRIVE_CM}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:src/main/resources/db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

#server:  port: 0 # cada microservicio define el suyo en su propio application.yml
